### PR TITLE
Upgrade TS client gen for date parsing fix

### LINKED ISSUE #2689: Instance disk metrics tab returns "something went wrong" error
This error happens after the metrics API responses have returned:

Image

 I do not see any error on nexus side which is consistent with the 200 responses I see on the browser console. Invoking some of the metrics queries using CLI also works for me:
```
$ oxide experimental timeseries query --query '{get virtual_disk:bytes_written; get virtual_disk:bytes_read } | filter timestamp > @now() - 30s| filter disk_id == "d8986332-65e3-43f0-a471-7366b2f1b5dc"' --project angela
{
  "tables": [
    {
      "name": "virtual_disk:bytes_written",
      "timeseries": {
        "17139298291928455619": {
          "fields": {
            "disk_id": {
              "type": "uuid",
              "value": "d8986332-65e3-43f0-a471-7366b2f1b5dc"
            },
            "silo_id": {
              "type": "uuid",
              "value": "7bd7623a-68ed-4636-8ecb-b59e3b068787"
            },
            "attached_instance_id": {
              "type": "uuid",
              "value": "3fbff45c-cf48-4dfd-9dc8-a4be0402e13a"
            },
            "project_id": {
              "type": "uuid",
              "value": "fe0da422-5c48-4b52-8010-f2fc401f090f"
            },
            "block_size": {
              "type": "u32",
              "value": 4096
            }
          },
          "points": {
            "start_times": [
              "2025-02-13T07:27:30.655996275Z",
              "2025-02-13T07:57:09.094344498Z",
              "2025-02-13T07:57:19.093842194Z"
            ],
            "timestamps": [
              "2025-02-13T07:57:09.094344498Z",
              "2025-02-13T07:57:19.093842194Z",
              "2025-02-13T07:57:29.094288161Z"
            ],
            "values": [
              {
                "metric_type": "delta",
                "values": {
                  "type": "integer",
                  "values": [
                    14655488,
                    245760,
                    49152
                  ]
                }
              }
            ]
          }
        }
      }
    },
    {
      "name": "virtual_disk:bytes_read",
      "timeseries": {
        "17139298291928455619": {
          "fields": {
            "silo_id": {
              "type": "uuid",
              "value": "7bd7623a-68ed-4636-8ecb-b59e3b068787"
            },
            "disk_id": {
              "type": "uuid",
              "value": "d8986332-65e3-43f0-a471-7366b2f1b5dc"
            },
            "attached_instance_id": {
              "type": "uuid",
              "value": "3fbff45c-cf48-4dfd-9dc8-a4be0402e13a"
            },
            "project_id": {
              "type": "uuid",
              "value": "fe0da422-5c48-4b52-8010-f2fc401f090f"
            },
            "block_size": {
              "type": "u32",
              "value": 4096
            }
          },
          "points": {
            "start_times": [
              "2025-02-13T07:27:30.655996275Z",
              "2025-02-13T07:57:09.094158697Z",
              "2025-02-13T07:57:19.093646123Z"
            ],
            "timestamps": [
              "2025-02-13T07:57:09.094158697Z",
              "2025-02-13T07:57:19.093646123Z",
              "2025-02-13T07:57:29.094093763Z"
            ],
            "values": [
              {
                "metric_type": "delta",
                "values": {
                  "type": "integer",
                  "values": [
                    64421888,
                    0,
                    0
                  ]
                }
              }
            ]
          }
        }
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by david-crespo**
Closes #2689

### CODE REVIEW

File: mock-api/disk.ts [hunk 1]
```diff
@@ -43,7 +43,8 @@ export const disks: Json<Disk>[] = [
     name: 'disk-3',
     description: "it's a third disk",
     project_id: project.id,
-    time_created: new Date().toISOString(),
+    // random hard-coded date with many digits to exercise date parsing
+    time_created: '2025-02-13T01:02:03.134789034233Z',
```
Comment (david-crespo) [inline mock-api/disk.ts:47]: confirmed this causes all disk tests to fail on main
