### PR TITLE
Read only disks, no size limit on local disks

### LINKED ISSUE #3009: Do not limit local disk to 1023 GiB
The current maximum local disk size validation for a maximum of 1023 GiB doesn't apply to local disks.

The way it is going to work (until we have more capacity/quota management things in place) is checking the zpool available capacity reported by inventory during instance creation. The saga fails when it can't find enough free space for creating the local disk being requested.

### PR DESCRIPTION
**Pull request by david-crespo**
Closes #3009

Threw this together real quick to de-risk and get a sense of the vibes. API built from https://github.com/oxidecomputer/omicron/pull/9731, which isn't merged yet and we're not sure if it will make it in for v18. This is built on top of #3005 because that has earlier API changes in it.

### Fun questions

* I put the read-only badge right in the name cell because it would be excessive to give it its own column, but really it doesn't feel great there either. Maybe if we had a read-only icon that you could hover on to get a label, it would work better in the name cell.
* `Read only: Yes` in the side modal looks silly, also not as grouped together with snapshot ID as I would like.
* Copy for the checkbox label (and possibly help text) — "Make disk read-only" is weird, as Ben points out

image

image

image

### CODE REVIEW

File: app/components/StateBadge.tsx [hunk 1]
```diff
@@ -90,3 +90,9 @@ export const DiskTypeBadge = (props: { diskType: DiskType; className?: string })
     {props.diskType}
   </Badge>
 )
+
+export const ReadOnlyBadge = () => (
+  <Badge color="neutral" className="relative">
+    read only
```
Comment (benjaminleonard) [inline app/components/StateBadge.tsx]: Such a silly nit, but I feel like even if it's made uppercase its good practice to case them properly

File: app/forms/disk-create.tsx [hunk 2]
```diff
@@ -289,7 +294,16 @@ const DiskSourceField = ({
           />
         )}
 
-        {diskSource.type === 'snapshot' && <SnapshotSelectField control={control} />}
+        {diskSource.type === 'snapshot' && (
+          <>
+            <SnapshotSelectField control={control} />
+            <div className="mt-2">
+              <CheckboxField name="diskBackend.diskSource.readOnly" control={control}>
+                Make disk read-only
```
Comment (benjaminleonard) [inline app/forms/disk-create.tsx:376]: "Make disk" is strange? Maybe just "Read-only"

Comment (david-crespo) [reply app/forms/disk-create.tsx:376]: I put that in there tentatively because when it was just read-only, it wasn't clear enough that read-only refers to the resulting disk. So I think we need something more than read-only. Unless we just make the label "Read only" and we put help text in there that says "Instances won't be able to write to this disk" or something. I am also slightly torn about the hyphen. Generally I feel like hyphen is right for regular copy, but when it's just "Read-only" by itself it looks bad.

**Comment by benjaminleonard** [comment]
The SSH key issue we can handle separately, will make an issue.

Read only badge in the table seems like the best of the options available, prefer to polluting the table with another column.

Read only: yes is weird. But not sure how to improve that whilst being honest about the API. If underneath we had "Read" and "Read and Write" as an access type that would feel more comfortable. Read only: True?

"Read-only" on its own is confusing when next to the listbox and moving it out of that container would probably require its own title. Again if the API was different we could use radios with the default being "Read and Write".

**Comment by david-crespo** [comment]
`TRUE` and `FALSE` as badges could work?

**Comment by hawkw** [comment]
> `TRUE` and `FALSE` as badges could work?

`RW` and `RO` are very horizontal-space-efficient...you could even be overly cute and do `rwx` and `r-x` like in `ls` output but that's probably a bit weird since we don't have an equivalent to the "execute" bit...
